repos:
    - repo: local
      hooks:
          - id: mypy
            name: mypy
            entry: mypy
            language: python
            types: [python]
            require_serial: true
            verbose: true
    - repo: https://github.com/gitleaks/gitleaks
      rev: v8.16.1
      hooks:
        - id: gitleaks
    - repo: https://github.com/PyCQA/flake8
      rev: 4.0.1
      hooks:
          - id: flake8
            args: ["--config", "src/.flake8", "src/rekono/", "src/tests/"]
