name: Code style
on:
  workflow_dispatch:
  pull_request:

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Flake8 check
        uses: py-actions/flake8@v2
        with:
          path: ./src

  mypy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'
      
      - name: Install Python dependencies
        run: |
          python -m pip install -U pip
          python -m pip install mypy==0.931
          python -m pip install -r requirements.txt
      
      - name: MyPy check
        run: mypy --namespace-packages --package rekono --install-types --non-interactive
