name: Release
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  publish-release:
    name: Publish Release
    runs-on: ubuntu-latest
    environment: Release
    defaults:
      run:
        working-directory: ./srcs
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Build Python package
        run: |
          python3 -m pip install twine
          python3 -m pip install -r requirements.txt
          python3 setup.py sdist
      
      - name: Upload package to PyPi
        run: twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
