name: Unit tests
on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'src/rekono/**'
      - 'src/tests/**'
      - 'src/requirements.txt'
      - 'src/requirements-dev.txt'

env:
  REQUIRED_COVERAGE: 95

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: python3 -m pip install -r requirements-dev.txt

      - name: Run unit tests
        run: coverage run -m pytest
      
      - name: Check coverage
        run: coverage report -m --skip-covered --omit="tests/*,rekono/client/*" --fail-under=$REQUIRED_COVERAGE
